const game = [
  {
    id: 1,
    title: "Astrobot: Rescue Mission",
    category: "Action, Platformer",
    price: 39.99,
    img: "/images/1.jpg",
    desc: "A fun and charming platformer where you control the adorable Astrobot, exploring worlds to rescue your friends. It won the Game of the Year award in 2024.",
    rating: 9.3,
    genre: "Action, Platformer",
    difficulty: "Easy",
    year: 2024,
    gameOfTheYear: true,
  },
  {
    id: 2,
    title: "Elden Ring",
    category: "Action, RPG",
    price: 59.99,
    img: "/images/2.jpg",
    desc: "An open-world action RPG by FromSoftware, known for its brutal difficulty and deep lore. A truly expansive and challenging game, which became one of the most iconic games of the year.",
    rating: 9.8,
    genre: "Action, RPG",
    difficulty: "Hard",
    year: 2022,
    gameOfTheYear: false,
  },
  {
    id: 3,
    title: "Sekiro: Shadows Die Twice",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/3.jpg",
    desc: "A challenging action-adventure game where you play as a lone shinobi on a quest to rescue his kidnapped lord. It won the Game of the Year award in 2019.",
    rating: 9.5,
    genre: "Action, Adventure",
    difficulty: "Hard",
    year: 2019,
    gameOfTheYear: true,
  },
  {
    id: 4,
    title: "Hogwarts Legacy",
    category: "Action, RPG",
    price: 69.99,
    img: "/images/4.jpg",
    desc: "An open-world RPG set in the Harry Potter universe, where you control a young wizard exploring Hogwarts and beyond. A game that captured the hearts of fans worldwide.",
    rating: 8.9,
    genre: "Action, RPG",
    difficulty: "Medium",
    year: 2023,
    gameOfTheYear: false,
  },
  {
    id: 5,
    title: "Detroit: Become Human",
    category: "Adventure, Sci-Fi",
    price: 49.99,
    img: "/images/5.jpg",
    desc: "An interactive drama and action-adventure game where you make decisions that affect the future of AI in a futuristic Detroit. A deeply emotional and thought-provoking experience.",
    rating: 9.2,
    genre: "Adventure, Sci-Fi",
    difficulty: "Medium",
    year: 2018,
    gameOfTheYear: false,
  },
  {
    id: 6,
    title: "Death Stranding",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/6.jpg",
    desc: "An open-world action game set in a post-apocalyptic world, where you play as Sam Porter Bridges on a mission to reconnect isolated cities. A unique experience with a focus on connection.",
    rating: 8.8,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2019,
    gameOfTheYear: false,
  },
  {
    id: 7,
    title: "The Callisto Protocol",
    category: "Horror, Action",
    price: 59.99,
    img: "/images/7.jpg",
    desc: "A survival horror game set on Jupiter's moon Callisto. You fight to survive in an environment overrun by terrifying creatures while uncovering dark secrets.",
    rating: 8.3,
    genre: "Horror, Action",
    difficulty: "Hard",
    year: 2022,
    gameOfTheYear: false,
  },
  {
    id: 8,
    title: "It Takes Two",
    category: "Action, Adventure, Co-op",
    price: 39.99,
    img: "/images/8.jpg",
    desc: "A cooperative action-adventure game where two players control a couple navigating through fantastical environments to repair their fractured relationship.",
    rating: 9.2,
    genre: "Action, Adventure, Co-op",
    difficulty: "Medium",
    year: 2021,
    gameOfTheYear: true,
  },
  {
    id: 9,
    title: "Fall Guys: Ultimate Knockout",
    category: "Action, Party",
    price: 19.99,
    img: "/images/9.jpg",
    desc: "A massively multiplayer online battle royale game where players compete in fun and chaotic obstacle courses to be the last one standing.",
    rating: 8.4,
    genre: "Action, Party",
    difficulty: "Easy",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 10,
    title: "Crash Bandicoot 4: It's About Time",
    category: "Action, Platformer",
    price: 39.99,
    img: "/images/10.jpg",
    desc: "The latest entry in the beloved platformer series. Join Crash and Coco as they travel through time to stop Dr. N. Brio and other villains.",
    rating: 8.9,
    genre: "Action, Platformer",
    difficulty: "Medium",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 11,
    title: "Tekken 7",
    category: "Fighting",
    price: 39.99,
    img: "/images/11.jpg",
    desc: "The latest entry in the legendary Tekken series. Battle through intense 1v1 fights with a cast of diverse characters.",
    rating: 9.0,
    genre: "Fighting",
    difficulty: "Medium",
    year: 2017,
    gameOfTheYear: false,
  },
  {
    id: 12,
    title: "Need for Speed: Heat",
    category: "Racing, Action",
    price: 59.99,
    img: "/images/12.jpg",
    desc: "An open-world racing game where you race against opponents during the day to earn money, and at night to build your reputation in illegal street races.",
    rating: 8.7,
    genre: "Racing, Action",
    difficulty: "Medium",
    year: 2019,
    gameOfTheYear: false,
  },
  {
    id: 13,
    title: "Black Myth: Wukong",
    category: "Action, RPG",
    price: 59.99,
    img: "/images/13.jpg",
    desc: "An upcoming action-RPG set in the world of Chinese mythology, where you play as Sun Wukong, the Monkey King, battling fierce enemies and exploring a vast mystical world.",
    rating: 8.8,
    genre: "Action, RPG",
    difficulty: "Medium",
    year: 2024,
    gameOfTheYear: false,
  },
  {
    id: 14,
    title: "Guardians of the Galaxy",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/14.jpg",
    desc: "An action-adventure game where you control Star-Lord and lead the Guardians on a mission to save the universe, with a great story and humorous dialogues.",
    rating: 8.8,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 15,
    title: "The Last of Us Part I",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/15.jpg",
    desc: "An emotionally charged story of survival and revenge, set in a post-apocalyptic world. The game follows Ellie as she navigates the harsh realities of a world overrun by infected.",
    rating: 9.5,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 16,
    title: "Red Dead Redemption 2",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/16.jpg",
    desc: "Step into the boots of Arthur Morgan, a member of the Van der Linde gang, in this epic tale of crime, loyalty, and survival in the American Wild West.",
    rating: 9.7,
    genre: "Action, Adventure",
    difficulty: "Hard",
    year: 2018,
    gameOfTheYear: true,
  },
  {
    id: 17,
    title: "Spider-Man: Miles Morales",
    category: "Action, Adventure",
    price: 49.99,
    img: "/images/17.jpg",
    desc: "Join Miles Morales as the new Spider-Man, exploring New York City while taking on a powerful new villain. A visually stunning and action-packed adventure.",
    rating: 9.0,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 18,
    title: "Demon's Souls",
    category: "Action, RPG",
    price: 69.99,
    img: "/images/18.jpg",
    desc: "A remake of the classic action-RPG that set the standard for difficult, rewarding gameplay. Explore a dark and foreboding world full of intense battles and deep lore.",
    rating: 9.2,
    genre: "Action, RPG",
    difficulty: "Hard",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 19,
    title: "Horizon Forbidden West",
    category: "Action, RPG",
    price: 69.99,
    img: "/images/19.jpg",
    desc: "A vast open-world adventure where you explore new regions, uncovering secrets, and battling mechanical creatures as you strive to save the world.",
    rating: 9.4,
    genre: "Action, RPG",
    difficulty: "Medium",
    year: 2022,
    gameOfTheYear: false,
  },
  {
    id: 20,
    title: "God of War Ragnarök",
    category: "Action, Adventure",
    price: 69.99,
    img: "/images/20.jpg",
    desc: "The sequel to the 2018 God of War, where Kratos and his son Atreus battle gods, monsters, and confront their fate in the wake of Ragnarök.",
    rating: 9.8,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2022,
    gameOfTheYear: false,
  },
  {
    id: 21,
    title: "Returnal",
    category: "Action, Roguelike",
    price: 69.99,
    img: "/images/21.jpg",
    desc: "A rogue-like third-person shooter set on an alien planet. Explore, fight, and die as you uncover the mysteries of your surroundings.",
    rating: 8.9,
    genre: "Action, Roguelike",
    difficulty: "Hard",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 22,
    title: "Resident Evil Village",
    category: "Horror, Action",
    price: 59.99,
    img: "/images/22.jpg",
    desc: "A first-person survival horror game where you fight for survival against grotesque creatures in a gothic village full of dark secrets.",
    rating: 9.1,
    genre: "Horror, Action",
    difficulty: "Medium",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 23,
    title: "Cyberpunk 2077",
    category: "RPG, Action",
    price: 59.99,
    img: "/images/23.jpg",
    desc: "Explore the futuristic Night City in this open-world RPG. Create your own character and engage in a narrative-driven experience full of action, choices, and consequences.",
    rating: 7.8,
    genre: "RPG, Action",
    difficulty: "Hard",
    year: 2020,
    gameOfTheYear: false,
  },
  {
    id: 24,
    title: "Ghost of Tsushima Director's Cut",
    category: "Action, Adventure",
    price: 69.99,
    img: "/images/24.jpg",
    desc: "Explore feudal Japan as a samurai fighting to protect your homeland from Mongol invaders. The Director's Cut adds additional story content and next-gen features.",
    rating: 9.2,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 25,
    title: "Deathloop",
    category: "Action, Shooter",
    price: 59.99,
    img: "/images/25.jpg",
    desc: "A time-looping first-person shooter where you play as Colt, a man stuck in a loop and forced to eliminate eight targets before the day resets.",
    rating: 8.9,
    genre: "Action, Shooter",
    difficulty: "Medium",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 26,
    title: "Gran Turismo 7",
    category: "Racing, Sports",
    price: 59.99,
    img: "/images/26.jpg",
    desc: "A realistic racing simulation game that delivers stunning graphics and detailed cars while offering a wide variety of racing events.",
    rating: 8.7,
    genre: "Racing, Sports",
    difficulty: "Medium",
    year: 2022,
    gameOfTheYear: false,
  },
  {
    id: 27,
    title: "Kena: Bridge of Spirits",
    category: "Action, Adventure",
    price: 39.99,
    img: "/images/27.jpg",
    desc: "A beautiful action-adventure game where you control Kena, a young spirit guide, and help lost spirits find peace in a vibrant forest world.",
    rating: 8.8,
    genre: "Action, Adventure",
    difficulty: "Easy",
    year: 2021,
    gameOfTheYear: false,
  },
  {
    id: 28,
    title: "Little Big Planet 3",
    category: "Platformer",
    price: 39.99,
    img: "/images/28.jpg",
    desc: "A charming platformer that lets you create, share, and play custom levels with friends. A delightful family-friendly game with endless creative possibilities.",
    rating: 8.6,
    genre: "Platformer",
    difficulty: "Easy",
    year: 2014,
    gameOfTheYear: false,
  },
  {
    id: 29,
    title: "The Witcher 3: Wild Hunt",
    category: "RPG, Action",
    price: 49.99,
    img: "/images/29.jpg",
    desc: "An open-world RPG where you play as Geralt of Rivia, a monster hunter, navigating a dark fantasy world full of rich stories, quests, and deep combat mechanics.",
    rating: 9.4,
    genre: "RPG, Action",
    difficulty: "Hard",
    year: 2015,
    gameOfTheYear: false,
  },
  {
    id: 30,
    title: "Uncharted 4: A Thief's End",
    category: "Action, Adventure",
    price: 59.99,
    img: "/images/30.jpg",
    desc: "The fourth entry in the Uncharted series, following Nathan Drake on an adventure around the world as he searches for lost treasure while facing dangerous enemies.",
    rating: 9.5,
    genre: "Action, Adventure",
    difficulty: "Medium",
    year: 2016,
    gameOfTheYear: true,
  },
];
export default game;
